AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30

Resources:
  MovieDbApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.ajulibe.java.SpringBootApi.awslambda.StreamLambdaHandler::handleRequest
      Runtime: java11
      MemorySize: 2048
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
          SPRING_DATASOURCE_URL: jdbc:postgresql://kandula.db.elephantsql.com/truuudey
          SPRING_DATASOURCE_USERNAME: truuudey
          SPRING_DATASOURCE_PASSWORD: fNS6tmVpfMc0Rbg6EWzNtdOqVu3n46Af
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: auth/{proxy+}
            Method: ANY
#  The below is for expressly stating name for the API gateway. SAM CLI already does hence the comment
#  ApiGateway:
#    Type: AWS::Serverless::Api
#    Properties:
#      Name: moviedb-api-gateway
#      StageName: Prod
#      DefinitionBody:
#        swagger: "2.0"
#        info:
#          title: "MovieDB API"
#        paths:
#          /{proxy+}:
#            x-amazon-apigateway-any-method:
#              parameters:
#                - name: "proxy"
#                  in: "path"
#                  required: true
#                  type: "string"
#              x-amazon-apigateway-integration:
#                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MovieDbApiFunction.Arn}/invocations
#                passthroughBehavior: "when_no_templates"
#                httpMethod: "POST"
#                type: "aws_proxy"
